Repository gnosis/dx-react, pull requests merged in 2018-10, with the labels that each got.

#381 Fix wrong network
  .travis.yml
  src/utils/index.ts
Labels: 1.0.5

#377 Hotfix/1.0.5
  .travis.yml
  package-lock.json
  package.json
  src/actions/tokenPair.ts
  src/assets/img/icons/providerIcons.js
  src/components/MenuWallet/index.tsx
  src/components/TokenItem/index.tsx
  src/containers/AppValidator/index.tsx
  src/containers/MenuWallet/index.ts
  src/containers/WalletIntegration/index.tsx
  src/globals/index.ts
  src/index.tsx
  src/public/google96dd53efdc540a07.html
  src/reducers/tokenPair.ts
  src/selectors/tokens.ts
  src/styles/components/navbar/_navbar.scss
  src/utils/index.ts
  travis/deploy_pull_request.sh
  travis/prepare_production_deployment.sh
  webpack.dev.config.js
  webpack.prod.config.js
Labels: 1.0.5, don't merge

#386 Hotfix/1.0.6
  .babelrc
  landing/assets/css/main.css
  landing/assets/css/main.css.map
  landing/assets/fonts/SpaceMono-Bold.ttf
  landing/assets/fonts/SpaceMono-Bold.woff2
  landing/assets/fonts/SpaceMono-Regular.ttf
  landing/assets/fonts/SpaceMono-Regular.woff2
  landing/assets/images/logo.svg
  landing/assets/images/logo_1.svg
  landing/assets/images/logo_2.svg
  landing/assets/images/logo_3.svg
  landing/assets/images/logo_4.svg
  landing/assets/images/slowtrade-symbol.svg
  landing/assets/images/slowtrade-text.svg
  landing/assets/js/main.js
  landing/assets/js/main.js.map
  landing/favicon.png
  landing/index.html
  package-lock.json
  package.json
  src/actions/blockchain.ts
  test/resources/token-lists/KOVAN/prod-token-list.json
  test/resources/token-lists/MAINNET/prod-token-list.json
  test/resources/token-lists/RINKEBY/dev-token-list.json
  test/resources/token-lists/RINKEBY/prod-token-list.json
  webpack.dev.config.js
  webpack.prod.config.js
Labels: don't merge

#391 Updated Cookies + Privacy Policy for slow.trade Mainnet
  src/assets/pdf/DutchX_Rinkeby_PrivacyPolicy.pdf
  src/assets/pdf/PrivacyPolicy.pdf
  src/components/ContentPage/index.tsx
  src/components/Cookies/index.tsx
  src/components/Disclaimer/index.tsx
  src/components/Footer/index.tsx
  src/components/Terms/index.tsx
Labels: 1.1.0

#406 add sortedTokenList selector
  src/components/TokenOverlay/index.tsx
Labels: don't merge
