Repository gnosis/dx-react, pull requests merged in 2018-05, with the labels that each got.

#239 Feature/dx 255 nowallet when mm locked
  src/actions/blockchain.ts
  src/components/Home/index.tsx
  src/components/NoWallet/index.tsx
  src/containers/Home/index.tsx
  src/containers/NoWallet/index.tsx
  src/globals/index.ts
  src/integrations/initialize.ts
  src/integrations/metamask/index.ts
  src/integrations/types.ts
  src/integrations/walletIntegration.ts
  src/reducers/auctions.ts
  src/reducers/blockchain.ts
  src/reducers/tokenBalances.ts
  src/selectors/blockchain.ts
  src/types/index.d.ts
  stories/NoWallet.tsx
  stories/TextSquare.tsx
  stories/helpers/mockStore.ts
Labels: WIP

#247 EXTENSION: Feature/dx 256 ongoing auction claiming and linking
  src/actions/blockchain.ts
  src/api/dutchx.ts
  src/api/index.ts
  src/api/types.ts
  src/components/AuctionStateHOC/index.tsx
  src/components/MenuAuctions/index.tsx
  src/containers/MenuAuctions/index.ts
  src/integrations/initialize.ts
  src/types/index.d.ts
  stories/MenuAuction.tsx
Labels: WIP

#240 changed formatting of reciprocal auctions display + removed Index Column
  src/actions/blockchain.ts
  src/api/dutchx.ts
  src/api/index.ts
  src/api/types.ts
  src/components/AuctionStateHOC/index.tsx
  src/components/MenuAuctions/index.tsx
  src/containers/MenuAuctions/index.ts
  src/integrations/initialize.ts
  src/types/index.d.ts
  stories/MenuAuction.tsx
Labels: mergable

#251 Hotfix/token decimals menu wallet
  src/api/index.ts
  src/api/types.ts
  src/components/MenuWallet/index.tsx
Labels: not yet ready

#253 Feature/new auction statuses
  src/components/AuctionPanel/index.tsx
  src/components/AuctionStateHOC/index.tsx
  src/globals/index.ts
  src/integrations/initialize.ts
Labels: mergable

#255 Feature/dx 273 ipfs download
  src/actions/ipfs.ts
  src/actions/tokenList.ts
  src/components/IPFSHOC/index.tsx
  src/components/Loader/index.tsx
  src/components/TokenUpload/index.tsx
  src/containers/TokenUpload/index.ts
  src/reducers/ipfs.ts
  src/styles/components/buttons/_buttons.scss
  src/styles/components/home/_home.scss
  src/styles/components/inputs/_inputs.scss
  src/styles/global.scss
Labels: Needs Review, mergable

#260 Feature/new routing
  package-lock.json
  package.json
  src/actions/index.ts
  src/actions/settings.js
  src/actions/settings.ts
  src/assets/404.svg
  src/assets/disclaimer.svg
  src/assets/tokens/DEFAULT_TOKEN.svg
  src/assets/tokens/TOKEN_LIST.svg
  src/components/App/index.tsx
  src/components/Disclaimer/index.tsx
  src/components/PageNotFound/index.tsx
  src/components/RedirectIf/index.tsx
  src/components/TokenItem/index.tsx
  src/containers/Disclaimer/index.ts
  src/containers/RedirectToDisclaimer/index.ts
  src/index.tsx
  src/reducers/settings.js
  src/reducers/settings.ts
  src/router.tsx
  src/styles/components/auction/_auction.scss
  src/styles/components/buttons/_buttons.scss
  src/styles/components/disclaimer/_disclaimer.scss
  src/styles/components/forms/_checkbox.scss
  src/styles/components/icons/_tokenIcons.scss
  src/styles/components/modals/_modals.scss
  src/styles/components/pagenotfound/_pagenotfound.scss
  src/styles/core/_base.scss
  src/styles/core/_fonts.scss
  src/styles/global.scss
  src/types/index.d.ts
Labels: mergable
